spring:
  application:
    name: ShopmeFrontEnd

  datasource:
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
    password: '0411'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 560405964736-l0e4g590lk4mmbh11ubtvqa4ru60k6m1.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1457015881948265
            client-secret: e53d9eca6b6f4aed017996cae2f0ae4f
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorization-uri: https://www.facebook.com/v13.0/dialog/oauth
            token-uri: https://graph.facebook.com/v13.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
            user-name-attribute: id

server:
  port: 80
  servlet:
    context-path: /Shopme
